### ISSUE TITLE
about library name / SONAME

### ISSUE THREAD

**Issue by rogers0** [redjack/ipset#41]
I'm trying to package libipset to debian, just like libcork: https://tracker.debian.org/pkg/libcork
However debian already has the library with the same name: https://tracker.debian.org/pkg/ipset
So I have to choose another name.

I'm going to use "libredjackipset", and SONAME for the latest version will be libredjackipset1.
If you have better name option, just let me know. Thank you!

**Comment by rogers0** [comment]
proposed packaging commit is already pushed to: https://github.com/rogers0/libredjackipset

**Comment by rogers0** [comment]
I changed my mind, I would call it libcorkipset.
If you have better name option, just let me know. Thank you!

**Comment by johnzachary** [comment]
"libcorkipset" is definitely a better choice.  However, if ipset is ever decoupled from libcork, then the name will have to change as well.

"libipaddrset" might not be a terrible alternative.

**Comment by rogers0** [comment]
Thanks for your feedback!

Do you have plan to remove libcork as dependency? :-P

I already packaged as libcorkipset, see: https://bugs.debian.org/827082#41
If I have to fix something big, I will consider to change to libipaddrset.

**Comment by johnzachary** [comment]
No plans to remove the libcork dependency.

**Comment by rogers0** [comment]
Since I'm just going to change library name / SONAME, the header file name won't be changed, and will be installed at `/usr/include/<new lib name>/`

When using the ipset library, we have to do either 
  `#include <libipaddrset/ipset.h>`
or
  `#include <libcorkipset/ipset.h>`

I think the formal one is much weird.
So I prefer the latter one, libcorkipset.

Could you kindly acknowledge this name, please?
Thank you!

**Comment by rogers0** [comment]
It's already uploaded to Debian sid, and successfully migrated to Debian testing (stretch).
- https://tracker.debian.org/pkg/libcorkipset

If you have any question or comment regarding to package name, please open a bug report in Debian.
Thank you!

Closing this issue here.
